services:
  - type: web
    name: agent-hub-backend
    env: python
    rootDir: .
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && python run.py
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_JWT_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: STRIPE_PRICE_ID
        sync: false
      - key: AGENT_CONTAINER_REGISTRY
        value: "docker.io"
      - key: BACKEND_CORS_ORIGINS
        value: "https://agent-hub-frontend.vercel.app,http://localhost:3000" 